/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardVisitorRouteImport } from './routes/dashboard.visitor'
import { Route as DashboardMemberRouteImport } from './routes/dashboard.member'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardVisitorMembershipRouteImport } from './routes/dashboard.visitor.membership'
import { Route as DashboardVisitorBookingsRouteImport } from './routes/dashboard.visitor.bookings'
import { Route as DashboardMemberProfileRouteImport } from './routes/dashboard.member.profile'
import { Route as DashboardMemberCoursesRouteImport } from './routes/dashboard.member.courses'
import { Route as DashboardMemberBookingsRouteImport } from './routes/dashboard.member.bookings'
import { Route as DashboardMemberAvailabilityRouteImport } from './routes/dashboard.member.availability'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminEventsRouteImport } from './routes/dashboard.admin.events'
import { Route as DashboardAdminBookingsRouteImport } from './routes/dashboard.admin.bookings'
import { Route as DashboardAdminApplicationsRouteImport } from './routes/dashboard.admin.applications'

const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVisitorRoute = DashboardVisitorRouteImport.update({
  id: '/visitor',
  path: '/visitor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemberRoute = DashboardMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVisitorMembershipRoute =
  DashboardVisitorMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => DashboardVisitorRoute,
  } as any)
const DashboardVisitorBookingsRoute =
  DashboardVisitorBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => DashboardVisitorRoute,
  } as any)
const DashboardMemberProfileRoute = DashboardMemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardMemberRoute,
} as any)
const DashboardMemberCoursesRoute = DashboardMemberCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardMemberRoute,
} as any)
const DashboardMemberBookingsRoute = DashboardMemberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardMemberRoute,
} as any)
const DashboardMemberAvailabilityRoute =
  DashboardMemberAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => DashboardMemberRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminEventsRoute = DashboardAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminBookingsRoute = DashboardAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminApplicationsRoute =
  DashboardAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => DashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/member': typeof DashboardMemberRouteWithChildren
  '/dashboard/visitor': typeof DashboardVisitorRouteWithChildren
  '/dashboard/admin/applications': typeof DashboardAdminApplicationsRoute
  '/dashboard/admin/bookings': typeof DashboardAdminBookingsRoute
  '/dashboard/admin/events': typeof DashboardAdminEventsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/member/availability': typeof DashboardMemberAvailabilityRoute
  '/dashboard/member/bookings': typeof DashboardMemberBookingsRoute
  '/dashboard/member/courses': typeof DashboardMemberCoursesRoute
  '/dashboard/member/profile': typeof DashboardMemberProfileRoute
  '/dashboard/visitor/bookings': typeof DashboardVisitorBookingsRoute
  '/dashboard/visitor/membership': typeof DashboardVisitorMembershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/member': typeof DashboardMemberRouteWithChildren
  '/dashboard/visitor': typeof DashboardVisitorRouteWithChildren
  '/dashboard/admin/applications': typeof DashboardAdminApplicationsRoute
  '/dashboard/admin/bookings': typeof DashboardAdminBookingsRoute
  '/dashboard/admin/events': typeof DashboardAdminEventsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/member/availability': typeof DashboardMemberAvailabilityRoute
  '/dashboard/member/bookings': typeof DashboardMemberBookingsRoute
  '/dashboard/member/courses': typeof DashboardMemberCoursesRoute
  '/dashboard/member/profile': typeof DashboardMemberProfileRoute
  '/dashboard/visitor/bookings': typeof DashboardVisitorBookingsRoute
  '/dashboard/visitor/membership': typeof DashboardVisitorMembershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/member': typeof DashboardMemberRouteWithChildren
  '/dashboard/visitor': typeof DashboardVisitorRouteWithChildren
  '/dashboard/admin/applications': typeof DashboardAdminApplicationsRoute
  '/dashboard/admin/bookings': typeof DashboardAdminBookingsRoute
  '/dashboard/admin/events': typeof DashboardAdminEventsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/member/availability': typeof DashboardMemberAvailabilityRoute
  '/dashboard/member/bookings': typeof DashboardMemberBookingsRoute
  '/dashboard/member/courses': typeof DashboardMemberCoursesRoute
  '/dashboard/member/profile': typeof DashboardMemberProfileRoute
  '/dashboard/visitor/bookings': typeof DashboardVisitorBookingsRoute
  '/dashboard/visitor/membership': typeof DashboardVisitorMembershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/membership'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/member'
    | '/dashboard/visitor'
    | '/dashboard/admin/applications'
    | '/dashboard/admin/bookings'
    | '/dashboard/admin/events'
    | '/dashboard/admin/users'
    | '/dashboard/member/availability'
    | '/dashboard/member/bookings'
    | '/dashboard/member/courses'
    | '/dashboard/member/profile'
    | '/dashboard/visitor/bookings'
    | '/dashboard/visitor/membership'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/membership'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/member'
    | '/dashboard/visitor'
    | '/dashboard/admin/applications'
    | '/dashboard/admin/bookings'
    | '/dashboard/admin/events'
    | '/dashboard/admin/users'
    | '/dashboard/member/availability'
    | '/dashboard/member/bookings'
    | '/dashboard/member/courses'
    | '/dashboard/member/profile'
    | '/dashboard/visitor/bookings'
    | '/dashboard/visitor/membership'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/membership'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/member'
    | '/dashboard/visitor'
    | '/dashboard/admin/applications'
    | '/dashboard/admin/bookings'
    | '/dashboard/admin/events'
    | '/dashboard/admin/users'
    | '/dashboard/member/availability'
    | '/dashboard/member/bookings'
    | '/dashboard/member/courses'
    | '/dashboard/member/profile'
    | '/dashboard/visitor/bookings'
    | '/dashboard/visitor/membership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/visitor': {
      id: '/dashboard/visitor'
      path: '/visitor'
      fullPath: '/dashboard/visitor'
      preLoaderRoute: typeof DashboardVisitorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/member': {
      id: '/dashboard/member'
      path: '/member'
      fullPath: '/dashboard/member'
      preLoaderRoute: typeof DashboardMemberRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/visitor/membership': {
      id: '/dashboard/visitor/membership'
      path: '/membership'
      fullPath: '/dashboard/visitor/membership'
      preLoaderRoute: typeof DashboardVisitorMembershipRouteImport
      parentRoute: typeof DashboardVisitorRoute
    }
    '/dashboard/visitor/bookings': {
      id: '/dashboard/visitor/bookings'
      path: '/bookings'
      fullPath: '/dashboard/visitor/bookings'
      preLoaderRoute: typeof DashboardVisitorBookingsRouteImport
      parentRoute: typeof DashboardVisitorRoute
    }
    '/dashboard/member/profile': {
      id: '/dashboard/member/profile'
      path: '/profile'
      fullPath: '/dashboard/member/profile'
      preLoaderRoute: typeof DashboardMemberProfileRouteImport
      parentRoute: typeof DashboardMemberRoute
    }
    '/dashboard/member/courses': {
      id: '/dashboard/member/courses'
      path: '/courses'
      fullPath: '/dashboard/member/courses'
      preLoaderRoute: typeof DashboardMemberCoursesRouteImport
      parentRoute: typeof DashboardMemberRoute
    }
    '/dashboard/member/bookings': {
      id: '/dashboard/member/bookings'
      path: '/bookings'
      fullPath: '/dashboard/member/bookings'
      preLoaderRoute: typeof DashboardMemberBookingsRouteImport
      parentRoute: typeof DashboardMemberRoute
    }
    '/dashboard/member/availability': {
      id: '/dashboard/member/availability'
      path: '/availability'
      fullPath: '/dashboard/member/availability'
      preLoaderRoute: typeof DashboardMemberAvailabilityRouteImport
      parentRoute: typeof DashboardMemberRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/events': {
      id: '/dashboard/admin/events'
      path: '/events'
      fullPath: '/dashboard/admin/events'
      preLoaderRoute: typeof DashboardAdminEventsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/bookings': {
      id: '/dashboard/admin/bookings'
      path: '/bookings'
      fullPath: '/dashboard/admin/bookings'
      preLoaderRoute: typeof DashboardAdminBookingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/applications': {
      id: '/dashboard/admin/applications'
      path: '/applications'
      fullPath: '/dashboard/admin/applications'
      preLoaderRoute: typeof DashboardAdminApplicationsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminApplicationsRoute: typeof DashboardAdminApplicationsRoute
  DashboardAdminBookingsRoute: typeof DashboardAdminBookingsRoute
  DashboardAdminEventsRoute: typeof DashboardAdminEventsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminApplicationsRoute: DashboardAdminApplicationsRoute,
  DashboardAdminBookingsRoute: DashboardAdminBookingsRoute,
  DashboardAdminEventsRoute: DashboardAdminEventsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardMemberRouteChildren {
  DashboardMemberAvailabilityRoute: typeof DashboardMemberAvailabilityRoute
  DashboardMemberBookingsRoute: typeof DashboardMemberBookingsRoute
  DashboardMemberCoursesRoute: typeof DashboardMemberCoursesRoute
  DashboardMemberProfileRoute: typeof DashboardMemberProfileRoute
}

const DashboardMemberRouteChildren: DashboardMemberRouteChildren = {
  DashboardMemberAvailabilityRoute: DashboardMemberAvailabilityRoute,
  DashboardMemberBookingsRoute: DashboardMemberBookingsRoute,
  DashboardMemberCoursesRoute: DashboardMemberCoursesRoute,
  DashboardMemberProfileRoute: DashboardMemberProfileRoute,
}

const DashboardMemberRouteWithChildren = DashboardMemberRoute._addFileChildren(
  DashboardMemberRouteChildren,
)

interface DashboardVisitorRouteChildren {
  DashboardVisitorBookingsRoute: typeof DashboardVisitorBookingsRoute
  DashboardVisitorMembershipRoute: typeof DashboardVisitorMembershipRoute
}

const DashboardVisitorRouteChildren: DashboardVisitorRouteChildren = {
  DashboardVisitorBookingsRoute: DashboardVisitorBookingsRoute,
  DashboardVisitorMembershipRoute: DashboardVisitorMembershipRoute,
}

const DashboardVisitorRouteWithChildren =
  DashboardVisitorRoute._addFileChildren(DashboardVisitorRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardMemberRoute: typeof DashboardMemberRouteWithChildren
  DashboardVisitorRoute: typeof DashboardVisitorRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardMemberRoute: DashboardMemberRouteWithChildren,
  DashboardVisitorRoute: DashboardVisitorRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
